### ISSUE TITLE
First checklist 

### ISSUE THREAD

**Issue by Hunta88** [Hunta88/BBC-News-Clone#1]
Create Outer Sections
- [x] Black section on Cookies
- [x] White Nav Bar (General)
- [x] Red Nav Bar (News)
- [x] White Space for Content
- [x] Black footer Section
