### ISSUE TITLE
Content Div Checklist

### ISSUE THREAD

**Issue by Hunta88** [Hunta88/BBC-News-Clone#5]
- [ ] 3 primary div Sections for News, Video & Links
- [ ] News Section has 2 Columns, first being 75% of width
- [ ] Video section is black box with rightmost 1/3 spaced for suggested videos
- [ ] 4x2 grid for Other news topics
